<?php

namespace Database\Seeders;

use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;

class UserSeeder extends Seeder
{
    public function run(): void
    {
        $users = [
            [
                'full_name' => 'Admin Carefund',
                'email' => 'admin@carefund.id',
                'password' => Hash::make('password123'),
                'phone' => '+6281234567890',
                'date_of_birth' => '1990-05-15',
                'gender' => 'male',
                'address' => 'Jl. Sudirman No. 123, Jakarta Pusat',
                'city' => 'Jakarta',
                'state' => 'DKI Jakarta',
                'country' => 'Indonesia',
                'is_verified' => true,
                'role' => 'admin',
            ],
            [
                'full_name' => 'Ahmad Fauzi',
                'email' => 'ahmad.fauzi@email.com',
                'password' => Hash::make('password123'),
                'phone' => '+6285678901234',
                'date_of_birth' => '1985-08-22',
                'gender' => 'male',
                'address' => 'Jl. Braga No. 45, Bandung',
                'city' => 'Bandung',
                'state' => 'Jawa Barat',
                'country' => 'Indonesia',
                'is_verified' => true,
                'role' => 'user',
            ],
            [
                'full_name' => 'Siti Nurhaliza',
                'email' => 'siti.nurhaliza@email.com',
                'password' => Hash::make('password123'),
                'phone' => '+6282345678901',
                'date_of_birth' => '1992-03-10',
                'gender' => 'female',
                'address' => 'Jl. Malioboro No. 78, Yogyakarta',
                'city' => 'Yogyakarta',
                'state' => 'DI Yogyakarta',
                'country' => 'Indonesia',
                'is_verified' => true,
                'role' => 'user',
            ],
            [
                'full_name' => 'Budi Santoso',
                'email' => 'budi.santoso@email.com',
                'password' => Hash::make('password123'),
                'phone' => '+6283456789012',
                'date_of_birth' => '1988-11-30',
                'gender' => 'male',
                'address' => 'Jl. Pemuda No. 12, Surabaya',
                'city' => 'Surabaya',
                'state' => 'Jawa Timur',
                'country' => 'Indonesia',
                'is_verified' => true,
                'role' => 'user',
            ],
            [
                'full_name' => 'Dewi Lestari',
                'email' => 'dewi.lestari@email.com',
                'password' => Hash::make('password123'),
                'phone' => '+6284567890123',
                'date_of_birth' => '1995-07-18',
                'gender' => 'female',
                'address' => 'Jl. Gajah Mada No. 34, Semarang',
                'city' => 'Semarang',
                'state' => 'Jawa Tengah',
                'country' => 'Indonesia',
                'is_verified' => true,
                'role' => 'user',
            ],
            [
                'full_name' => 'Rico Hermawan',
                'email' => 'rico.hermawan@email.com',
                'password' => Hash::make('password123'),
                'phone' => '+6285678901235',
                'date_of_birth' => '1993-12-05',
                'gender' => 'male',
                'address' => 'Jl. Asia Afrika No. 56, Makassar',
                'city' => 'Makassar',
                'state' => 'Sulawesi Selatan',
                'country' => 'Indonesia',
                'is_verified' => true,
                'role' => 'user',
            ],
            [
                'full_name' => 'Nila Safitri',
                'email' => 'nila.safitri@email.com',
                'password' => Hash::make('password123'),
                'phone' => '+6286789012345',
                'date_of_birth' => '1991-09-25',
                'gender' => 'female',
                'address' => 'Jl. Diponegoro No. 89, Medan',
                'city' => 'Medan',
                'state' => 'Sumatera Utara',
                'country' => 'Indonesia',
                'is_verified' => true,
                'role' => 'user',
            ],
            [
                'full_name' => 'Joko Pramono',
                'email' => 'joko.pramono@email.com',
                'password' => Hash::make('password123'),
                'phone' => '+6287890123456',
                'date_of_birth' => '1987-04-12',
                'gender' => 'male',
                'address' => 'Jl. Gatot Subroto No. 101, Jakarta',
                'city' => 'Jakarta',
                'state' => 'DKI Jakarta',
                'country' => 'Indonesia',
                'is_verified' => false,
                'role' => 'user',
            ],
            [
                'full_name' => 'Rina Kusuma',
                'email' => 'rina.kusuma@email.com',
                'password' => Hash::make('password123'),
                'phone' => '+6288901234567',
                'date_of_birth' => '1994-06-20',
                'gender' => 'female',
                'address' => 'Jl. Sultan Agung No. 22, Palembang',
                'city' => 'Palembang',
                'state' => 'Sumatera Selatan',
                'country' => 'Indonesia',
                'is_verified' => true,
                'role' => 'user',
            ],
            [
                'full_name' => 'Hendra Wijaya',
                'email' => 'hendra.wijaya@email.com',
                'password' => Hash::make('password123'),
                'phone' => '+6289012345678',
                'date_of_birth' => '1989-01-08',
                'gender' => 'male',
                'address' => 'Jl. Thamrin No. 45, Jakarta',
                'city' => 'Jakarta',
                'state' => 'DKI Jakarta',
                'country' => 'Indonesia',
                'is_verified' => true,
                'role' => 'user',
            ],
        ];

        foreach ($users as $user) {
            User::create($user);
        }
    }
}